clean up old workflow

diff --git a/.github/workflows/frontend-deploy.yml b/.github/workflows/frontend-deploy.yml
--- a/.github/workflows/frontend-deploy.yml
+++ b/.github/workflows/frontend-deploy.yml
@@ -32,6 +32,10 @@ jobs:
         if: steps.cache.outputs.cache-hit != 'true'
         run: npm install
 
+      - name: Check for build env # fail if not found
+        if: ${{ !vars.REACT_APP_API_URL || vars.REACT_APP_API_URL.length < 1}}
+        run: echo "Missing REACT_APP_API_URL environment variable" && exit 1
+
       - name: Build react to webpage
         run: npm run build
         env:
